### ISSUE TITLE
Use TreeWalker

### ISSUE THREAD

**Issue by fregante** [fisker/get-text-nodes#938]
I just noticed you have this module named exactly like something I wrote for Refined GitHub, except mine uses createTreeWalker to get and filter nodes. You might be interested:

https://github.com/sindresorhus/refined-github/blob/6cd801086af7e3c0c75360bbab943c77c9c3c7ff/source/helpers/get-text-nodes.ts#L2

**Comment by fisker** [comment]
Wow, didn't know that, thanks!
